ALTER TABLE users ADD COLUMN email VARCHAR(255) UNIQUE DEFAULT NULL AFTER password;
ALTER TABLE users ADD COLUMN verification_code VARCHAR(255) DEFAULT NULL AFTER email;
ALTER TABLE users ADD COLUMN is_verified TINYINT(1) DEFAULT 0 AFTER verification_code;
